#!/bin/bash


BIN_PATH=/usr/local/bin/boilerplate
HTML_PATH=/usr/local/boilerplate

mkdir $HTML_PATH && cat ./index.html > $HTML_PATH/index.html && cat boilerplate.sh > $BIN_PATH && chmod +x $BIN_PATH 

  
