#!/bin/bash

BIN_FILE=/usr/local/bin/boilerplate
BOILER=/usr/local/boilerplate


if [ -f $BIN_FILE ] || [ -d $BOILER ]; then
    rm -rf $BIN_FILE
    rm -rf $BOILER
    echo "done"
else
    echo "boilerplate not installed"   
fi

